name: push-deploy-world

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  push-or-pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy'
        if: github.event_name != 'false'
        uses: ./.github/workflows/deploy-with-version.yml
        with:
          dcl-sdk-package: '@dcl/sdk@latest'
        env:
          SDK_TEAM_S3_BUCKET: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          SDK_TEAM_AWS_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          SDK_TEAM_AWS_SECRET: ${{ secrets.SDK_TEAM_AWS_SECRET }}
          SDK_TEAM_S3_BASE_URL: ${{ secrets.SDK_TEAM_S3_BASE_URL }}
          AB_TOKEN: ${{ secrets.AB_TOKEN }}
